### ISSUE TITLE
Failure parsing the version

### ISSUE THREAD

**Issue by NuxRo** [mad-ady/smokeping-speedtest#18]
Hi,

I've installed the plugins and restarted smokeping, however it fails to start due to:

```
smokeping[3176]: ERROR: output of '/usr/bin/speedtest --version' does not return a meaningful version number. Is speedtest installed?
smokeping[3176]: at (eval 60) line 1.
```
The output returned by speedtest --version is:
```
# /usr/bin/speedtest --version
speedtest-cli 2.1.2
Python 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

**Comment by mad-ady** [comment]
Do you get this error with Sievel's speedtest (speedtest probe), or with Ookla's speedtest-cli (speedtestcli probe)?

**Comment by NuxRo** [comment]
Sievel's (installed this one as per your readme). Should I try the other one?

**Comment by mad-ady** [comment]
Ok. How does your probe configuration look like? Are you using
```
+ speedtest
```
or
```
+ speedtestcli
```

You should be using speedtest as a probe name, otherwise it tries to parse
the output expected from the ookla client.
Regarding which one you should use - the ookla client seems to return more
consistent results (better upload measurements).

**Comment by NuxRo** [comment]
Ah, hang on.. my fault, didn't realise the sample config in the readme is for both clients, a bit confused as Sievel's installs both speedtest and speedtest-cli binaries/paths. Feel free to close this.

**Comment by mad-ady** [comment]
No worries. Glad it's sorted!
